default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  pool: 5
  username: postgres
  password: LakeDev2025
  port: 5432

development:
  <<: *default
  database: messaging_api_development

test:
  <<: *default
  database: messaging_api_test

production:
  <<: *default
  database: messaging_api_production
  username: postgres
  password: <%= ENV['MESSAGING_API_DATABASE_PASSWORD'] %>
